### ISSUE TITLE
Создание приложения на основе скаффолдера.

### ISSUE THREAD

**Issue by SilentImp** [FrontenderMagazineDevelopment/backoffice.schedule.frontender.info#8]
Пример скафолдера: http://github.com/zeit/next.js/

AC:

- [x] есть репозиторий проекта
- [x] репозиторий содержит запускающееся приложение
- [x] в README.md инструкция по запуску

**Comment by SilentImp** [comment]
Создал репозиторий https://github.com/FrontenderMagazineDevelopment/backoffice.schedule.frontender.info

**Comment by vostrik** [comment]
@SilentImp Готово. Так же настроил линтинг через Standard JS.
